spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: prometheus

# logging:
#   level:
#     sql: debug