spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

#logging:
#  level:
#    sql: debug
#    org.hibernate.orm.jdbc.bind: trace

#logging:
#  level:
#    kr:
#      or:
#        kosa:
#          cmsplusmain: DEBUG
