server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: cmsplus-main
  jwt:
    secret: ${JWT_SECRET}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 10  # 기본 페이지 사이즈는 10이므로 batchsize 10
    open-in-view: false
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

  sql:
    init:
      mode: always

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      consent-bucket: ${S3_CONSENT_BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

kafkaServer:
  ip: ${KAFKASERVER_IP}

kafkaGroup:
  paymentResultGroup: ${PAYMENT_RESULT_GROUP}

kafkaTopic:
  messagingTopic: ${MESSAGING_TOPIC}
  paymentTopic: ${PAYMENT_TOPIC}

host:
  front: https://www.hyosungcmsplus.site


logging:
  level:
    kr:
      or:
        kosa:
          cmsplusmain: DEBUG