spring:
  application:
    name: cmsplus-main
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdba
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmsplusmain?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1004

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false


logging:
  level:
    org.hibernate.orm.jdbc.bind: trace


coolsms:
  api-key: NCS6FSXZJNQ2W4VB
  api-secret: PW7L7IUM5REUVNL0HYKANDIL7XSLBRHK
  sender-number: 01026270378

cloud:
  aws:
    s3:
      bucket: cmssignawsbucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA5FTZDY5XEBI6PM6M
      secretKey: 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
