name: Commit Message Check

on:
  push:
    branches:
      - '*'

permissions: #github actions bot에게 권한 열기
  contents: write
  pages: write
  id-token: write

jobs:
  commit_message_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read Commit Regular Expression
        id: read_commit_regex
        run: |
          commit_msg_regex=$(cat ./.github/commit_lint.txt)
          echo "Commit Regular Expression: $commit_msg_regex"
          echo "::set-output name=commit_regex::$commit_msg_regex"

      - name: Validate Commit Message
        id: validate_commit_message
        run: |
          commit_msg=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "Commit Message: $commit_msg"
          commit_regex="${{ steps.read_commit_regex.outputs.commit_regex }}"
          if [[ ! "$commit_msg" =~ $commit_regex ]]; then
            echo "Invalid commit message format."
            echo "::set-output name=valid_commit::false"
          else
            echo "Commit message is valid."
            echo "::set-output name=valid_commit::true"
          fi

      - name: Cancel Push if Commit Message Invalid
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
        if: steps.validate_commit_message.outputs.valid_commit == 'false'
        run: |
          git push --delete origin ${{ github.ref }}

