name: Rollback Invalid Commit

on:
  push:
    branches:
      - '*'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  rollback_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read Commit Regular Expression
        id: read_commit_regex
        run: |
          commit_msg_regex=$(cat .github/commit_lint.txt)
          echo "Commit Regular Expression: $commit_msg_regex"
          echo "::set-output name=commit_regex::$commit_msg_regex"

      - name: Validate Commit Message
        id: validate_commit_message
        run: |
          commit_msg=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "Commit Message: $commit_msg"
          commit_regex="${{ steps.read_commit_regex.outputs.commit_regex }}"
          if [[ ! "$commit_msg" =~ $commit_regex ]]; then
            echo "Invalid commit message format."
            exit 1
          else
            echo "Commit message is valid."
          fi

      - name: Rollback Invalid Commit
        if: failure() # 이전 단계에서 실패한 경우에만 실행됩니다 (즉, 유효하지 않은 커밋 메시지가 있을 때).
        run: |
          current_branch=$(echo ${{ github.ref }} | awk -F'/' '{print $3}')
          git fetch origin
          git reset --hard origin/$current_branch
          git push --force origin $current_branch
