name: PAYMENT CICD

on:
  push:
    branches:
      - dev
    paths:
      - 'server-payment/**'

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: t3-back-paymentecr
  ECS_CLUSTER: t3-back-ecscluster
  ECS_CONTAINER: t3-back-paymentcontainer
  ECS_SERVICE: t3-back-ecscluster/t3-back-paymentservice
  ECS_TASK_DEFINITION: infra/task-definition-payment.json

permissions:
  contents: read

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}    

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant Grant Permission
      run: chmod +x server-payment/gradlew

    - name: Inject secure
      run: echo "${{ secrets.PAYMENT_SECURE_DEV }}" > server-payment/src/main/resources/secure.properties

    - name: Build with Gradle
      run: |
        cd server-payment
        ./gradlew clean build

    - name: Replace AWS ID
      run: |
        sed -i "s/{AWS_ACCOUNT_ID}/${{ secrets.AWS_ACCOUNT_ID }}/g" ${{ env.ECS_TASK_DEFINITION }}

    - name: Login ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./server-payment
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Image ID to ECS TASK
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.ECS_CONTAINER }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true