name: Slack Alarm Webhook

on:
  pull_request:
    types: [opened, closed]

jobs:
  mention_notification:
    name: Mention Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_ICON_EMOJI: ':github:'
        with:
          args: |
            {{
              "attachments": [
                {
                  "color": "{{#if eq github.event_name 'pull_request'}}{{#if eq github.event.action 'opened'}}good{{else}}warning{{/if}}{{else}}danger{{/if}}",
                  "author_name": "Pull Request Event",
                  "title": "Pull Request #{{ github.event.pull_request.number }}",
                  "title_link": "{{ github.event.pull_request.html_url }}",
                  "text": "{{#if eq github.event.action 'opened'}}OPEN{{else}}CLOSE{{/if}}"
                }
              ]
            }}




# name: Slack Alarm Webhook

# on:
#   pull_request:
#     # types: [opened, reopened, edited, closed, review_requested]
#     types: [opened, closed]

#   # pull_request_review:
#   #   types: [submitted]
#   # pull_request_review_comment:
#   #   types: [created, edited]

# jobs:
#   mention_notification:
#     name: Mention Notification
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send notification to Slack
#         uses: rtCamp/action-slack-notify@master
#         env:
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
#           SLACK_USERNAME: 'GitHub Actions'
#           SLACK_ICON_EMOJI: ':github:'
#         with:
#           args: ${{ toJson(github.event) }}