name: Slack Alarm Webhook

on:
  pull_request:
    types: [opened, closed]

jobs:
  mention_notification:
    name: Mention Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_ICON_EMOJI: ':github:'
        # Constructing a custom message based on the event action
        steps:
          - name: Set PR status
            id: pr_status
            run: |
              if [ ${{ github.event.action }} == 'opened' ]; then
                echo "::set-output name=status::OPEN"
              else
                echo "::set-output name=status::CLOSE"
              fi
          - name: Send Slack notification
            uses: rtCamp/action-slack-notify@master
            with:
              args: |
                {
                  "text": "Pull Request #${{ github.event.pull_request.number }} ${{ steps.pr_status.outputs.status }}",
                  "attachments": [
                    {
                      "color": "${{ github.event.action == 'opened' ? 'good' : 'warning' }}",
                      "author_name": "Pull Request Event",
                      "title": "Pull Request #${{ github.event.pull_request.number }}",
                      "title_link": "${{ github.event.pull_request.html_url }}",
                      "text": "${{ steps.pr_status.outputs.status }}"
                    }
                  ]
                }
