name: Slack Alarm Webhook

on:
  pull_request:
    types: [opened, closed]

jobs:
  mention_notification:
    name: Mention Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_ICON_EMOJI: ':github:'
        # Constructing a custom message based on the event action
        with:
          args: |
            {
              "text": "Pull Request #${{ github.event.pull_request.number }} ${{
                github.event.action == 'opened' ? 'opened' : 'closed'
              }}",
              "attachments": [
                {
                  "color": "${{ github.event.action == 'opened' ? 'good' : 'warning' }}",
                  "author_name": "Pull Request Event",
                  "title": "Pull Request #${{ github.event.pull_request.number }}",
                  "title_link": "${{ github.event.pull_request.html_url }}",
                  "text": "${{ github.event.action == 'opened' ? 'OPEN' : 'CLOSE' }}"
                }
              ]
            }
