name: Slack PR Webhook

on:
  pull_request:
    types: [opened, closed]

jobs:
  slack_pr_webhook:
    name: Slack PR Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Set Status
        id: status
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "::set-output name=footer::[OPEN]"
          elif [ "${{ github.event.action }}" == "closed" ]; then
            echo "::set-output name=footer::[CLOSE]"
          fi

      - name: Send Webhook
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_ICON_EMOJI: ':github:'
          SLACK_FOOTER: ${{ steps.status.outputs.footer }}
