name: Slack Alarm Webhook

on:
  pull_request:
    types: [opened, closed]

jobs:
  mention_notification:
    name: Mention Notification
    runs-on: ubuntu-latest
    steps:
      - name: Set Footer based on PR type
        id: set-footer
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "::set-output name=footer::[OPEN]"
          elif [ "${{ github.event.action }}" == "closed" ]; then
            echo "::set-output name=footer::[CLOSE]"
          fi

      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_ICON_EMOJI: ':github:'
          SLACK_FOOTER: ${{ steps.set-footer.outputs.footer }}
