name: Slack Alarm Webhook

on:
  pull_request:
    types: [opened, closed]

jobs:
  mention_notification:
    name: Mention Notification
    runs-on: ubuntu-latest
    steps:
      - name: Determine PR state
        id: pr_state
        run: echo "::set-output name=state::${{ github.event_name }}"

      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_ICON_EMOJI: ':github:'
          SLACK_FOOTER: ${{ if eq(steps.pr_state.outputs.state, 'pull_request') }}[OPEN]${{ else }}[CLOSE]${{ endif }}
        with:
          args: ${{ toJson(github.event) }}
