name: Sync QA to Prod

on:
  push:
    branches:
      - qa

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: qa

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge qa into prod
      run: |
        git checkout prod
        git merge qa --no-ff --commit -m "[Automated merge from qa to prod]"
    
    - name: Push changes to prod
      run: |
        git push origin prod