name: Sync Main to Rel

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Fetch all branches
      run: git fetch origin

    - name: Checkout rel branch
      run: git checkout -b rel origin/rel

    - name: Merge main into rel
      run: |
        git merge main --strategy-option theirs

    - name: Push changes to rel
      env:
        GITHUB_TOKEN: ${{ secrets.CMSPLUS_TOKEN }}
      run: git push origin rel
